services:
     php-oop-exercice:
          container_name: php-oop-exercice
          build: .
          volumes: 
               - ./app:/var/www/html
               - ./logs:/var/log/apache2/
          ports:
               - 8080:80
          depends_on:
              - php-oop-exercice-db
     php-oop-exercice-db:
          container_name: php-oop-exercice-db
          image: mysql:latest
          restart: unless-stopped
          environment:
               MYSQL_DATABASE: 'db'
               # So you don't have to use root, but you can if you like
               MYSQL_USER: 'user'
               # You can use whatever password you like
               MYSQL_PASSWORD: 'password'
               # Password for root access
               MYSQL_ROOT_PASSWORD: 'password'
          ports:
               - 3307:3306
          volumes:
               - ./mysql:/var/lib/mysql